FROM node:18-alpine AS builder

WORKDIR /build

COPY gm/package.json gm/package-lock.json* ./
RUN npm install

COPY gm/ .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /build/dist /usr/share/nginx/html
COPY deploy/nginx-gm.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
