FROM node:18-alpine AS builder

WORKDIR /build

COPY client/package.json client/package-lock.json* ./
RUN npm install

COPY client/ .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /build/dist /usr/share/nginx/html
COPY deploy/nginx-client.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
