export const meta = {
  name: "agentgame-self-improve",
  description: "Autonomous improvement loop for agentGame framework - implements, tests, and commits improvements iteratively"
};

const BACKLOG_PATH = "IMPROVEMENT_BACKLOG.json";
const REPORT_PATH = "SELF_IMPROVE_REPORT.md";
const MAX_ITERATIONS = 40;

async function loadBacklog() {
  const raw = await readFile(BACKLOG_PATH);
  if (!raw) throw new Error("Backlog not found at " + BACKLOG_PATH);
  return JSON.parse(raw);
}

async function saveBacklog(backlog) {
  // Re-read disk version to merge any externally-added tasks
  const diskRaw = await readFile(BACKLOG_PATH);
  if (diskRaw) {
    const diskBacklog = JSON.parse(diskRaw);
    const knownIds = new Set(backlog.map(t => t.id));
    const externalTasks = diskBacklog.filter(t => !knownIds.has(t.id));
    if (externalTasks.length > 0) {
      backlog.push(...externalTasks);
      await log(`Merged ${externalTasks.length} external tasks: ${externalTasks.map(t => t.id).join(", ")}`);
    }
  }
  await writeFile(BACKLOG_PATH, JSON.stringify(backlog, null, 2));
}

async function getNextTask(backlog) {
  const pending = backlog.filter(t => t.status === "pending");
  pending.sort((a, b) => a.priority - b.priority);
  return pending[0] || null;
}

async function runTests() {
  const result = await agent(
    `Run the Go test suite for the server at D:\\dev\\my_project\\agentGame\\server.
    
Steps:
1. cd to D:\\dev\\my_project\\agentGame\\server
2. Run: go test ./internal/tests/ -v -count=1 -timeout 120s
3. Capture ALL output
4. If tests fail, analyze the failures and report exactly which tests failed and why
5. Also run: go vet ./... to check for code issues
6. Report: total tests, passed, failed, any vet warnings

Return a structured report with:
- test_command: the command run
- total_tests: number
- passed: number  
- failed: number
- failures: array of {test_name, error_message} for any failures
- vet_ok: boolean
- vet_warnings: array of strings
- overall: "PASS" or "FAIL"`,
    { subagent_type: "general" }
  );
  return result;
}

async function commitChanges(taskId, title) {
  const result = await agent(
    `Commit the current changes in D:\\dev\\my_project\\agentGame to git.

Steps:
1. Run git status to see what changed
2. Run git diff to review changes
3. Stage all changed files with: git add -u (only tracked files, not untracked)
4. Also stage any new test files that were created
5. Create a commit with message: "feat(${taskId}): ${title}"
6. Run git status to verify

Return:
- files_changed: list of changed files
- commit_hash: the new commit hash
- message: the commit message used`,
    { subagent_type: "general" }
  );
  return result;
}

async function appendReport(entry) {
  let existing = await readFile(REPORT_PATH);
  if (!existing) {
    existing = `# AgentGame Self-Improvement Report\n\nGenerated by autonomous improvement loop.\n\n---\n\n`;
  }
  existing += entry + "\n\n---\n\n";
  await writeFile(REPORT_PATH, existing);
}

function makeImplementPrompt(task, backlogContext) {
  return `You are implementing an improvement for the agentGame project at D:\\dev\\my_project\\agentGame.

## YOUR TASK
**${task.id}: ${task.title}**
Priority: ${task.priority}
Category: ${task.category}

**Description**: ${task.description}

**Files to modify**: ${JSON.stringify(task.files)}
**Test file**: ${task.test_file || "none (use existing tests)"}

## PROJECT CONTEXT
- Monorepo: server/ (Go/Gin/GORM), client/ (Phaser 3), gm/ (Vue 3 + Element Plus)
- Go module: github.com/ddc-111/agentGame/server
- Entry: server/cmd/gameserver/main.go
- Models: server/internal/database/models/models.go (17 models, all have BaseModel)
- Repository: server/internal/database/repository/repository.go
- Tests use in-memory SQLite: server/internal/tests/fixtures.go has setupTestServer()
- Entity codes: snake_case with prefix (scene_*, npc_*, item_*, etc.)
- No linter/formatter configured yet

## EXISTING BACKLOG CONTEXT
${backlogContext}

## INSTRUCTIONS
1. Read all files you need to modify FIRST
2. Understand the current code structure and patterns
3. Implement the improvement following existing code conventions
4. Write comprehensive tests (if test_file specified)
5. Make sure all code compiles: run "go build ./..." in server/
6. Run "go vet ./..." to check for issues
7. DO NOT add comments to code unless absolutely necessary
8. Follow existing error handling patterns
9. Keep changes focused - don't refactor unrelated code

## WHAT TO RETURN
Report exactly what you changed:
- Files modified and what changed in each
- New files created
- Tests written and what they cover
- Any build/vet issues found and fixed
- Any risks or follow-up items`;
}

// ========== MAIN LOOP ==========

const backlog = await loadBacklog();
const results = [];
let iteration = 0;

await phase("Self-Improvement Loop Starting");
await log(`Loaded backlog with ${backlog.length} tasks, ${backlog.filter(t => t.status === "pending").length} pending`);

while (iteration < MAX_ITERATIONS) {
  const task = await getNextTask(backlog);
  if (!task) {
    await log("No more pending tasks. All done!");
    break;
  }

  iteration++;
  await phase(`Iteration ${iteration}: ${task.id} - ${task.title}`);
  await log(`Starting ${task.id} (priority ${task.priority}, category ${task.category})`);

  // Step 1: Implement
  const pendingTasks = backlog.filter(t => t.status === "pending").map(t => `${t.id}: ${t.title}`).join("\n");
  const implResult = await agent(
    makeImplementPrompt(task, pendingTasks),
    { subagent_type: "general", timeout_ms: 600000 }
  );

  // Step 2: Test
  await log(`Implementation done for ${task.id}. Running tests...`);
  const testResult = await runTests();

  let parsedTest;
  try {
    parsedTest = typeof testResult === "string" ? JSON.parse(testResult) : testResult;
  } catch {
    parsedTest = { overall: "UNKNOWN", raw: testResult };
  }

  const testsPassed = parsedTest.overall === "PASS" || parsedTest.failed === 0;

  // Step 3: Update backlog status
  if (testsPassed) {
    task.status = "completed";
    await log(`Tests PASSED for ${task.id}. Committing...`);

    // Step 4: Commit
    const commitResult = await commitChanges(task.id, task.title);

    // Step 5: Report
    const reportEntry = `## ${task.id}: ${task.title}
- **Status**: COMPLETED
- **Iteration**: ${iteration}
- **Category**: ${task.category}
- **Description**: ${task.description}
- **Tests**: ${parsedTest.passed || "?"} passed, ${parsedTest.failed || 0} failed
- **Implementation**: ${typeof implResult === "string" ? implResult.substring(0, 500) : JSON.stringify(implResult).substring(0, 500)}
- **Commit**: ${typeof commitResult === "string" ? commitResult.substring(0, 300) : JSON.stringify(commitResult).substring(0, 300)}`;

    await appendReport(reportEntry);
    results.push({ task: task.id, status: "completed", tests: "PASS" });
  } else {
    task.status = "needs_fix";
    await log(`Tests FAILED for ${task.id}. Marking for fix.`);

    // Try to fix
    const fixResult = await agent(
      `The following tests failed after implementing ${task.id}: ${task.title}

Test results: ${JSON.stringify(parsedTest, null, 2)}

Previous implementation details: ${typeof implResult === "string" ? implResult.substring(0, 2000) : JSON.stringify(implResult).substring(0, 2000)}

Fix the failing tests. Read the test files and implementation files, understand the failures, and fix them.
Run tests again after fixing. Return the updated test results.`,
      { subagent_type: "general", timeout_ms: 600000 }
    );

    // Re-test after fix
    const retestResult = await runTests();
    let parsedRetest;
    try {
      parsedRetest = typeof retestResult === "string" ? JSON.parse(retestResult) : retestResult;
    } catch {
      parsedRetest = { overall: "UNKNOWN", raw: retestResult };
    }

    if (parsedRetest.overall === "PASS" || parsedRetest.failed === 0) {
      task.status = "completed";
      await log(`Fix succeeded for ${task.id}. Committing...`);
      const commitResult = await commitChanges(task.id, task.title + " (fix)");

      const reportEntry = `## ${task.id}: ${task.title}
- **Status**: COMPLETED (after fix)
- **Iteration**: ${iteration}
- **Category**: ${task.category}
- **Description**: ${task.description}
- **Tests**: ${parsedRetest.passed || "?"} passed, ${parsedRetest.failed || 0} failed
- **Fix applied**: Yes
- **Commit**: ${typeof commitResult === "string" ? commitResult.substring(0, 300) : JSON.stringify(commitResult).substring(0, 300)}`;

      await appendReport(reportEntry);
      results.push({ task: task.id, status: "completed-after-fix", tests: "PASS" });
    } else {
      task.status = "failed";
      await log(`Fix also failed for ${task.id}. Skipping.`);

      const reportEntry = `## ${task.id}: ${task.title}
- **Status**: FAILED (skipped)
- **Iteration**: ${iteration}
- **Category**: ${task.category}
- **Test failures**: ${JSON.stringify(parsedRetest.failures || parsedRetest.raw || "unknown")}`;

      await appendReport(reportEntry);
      results.push({ task: task.id, status: "failed", tests: "FAIL" });
    }
  }

  // Save progress
  await saveBacklog(backlog);

  await log(`Iteration ${iteration} complete. ${backlog.filter(t => t.status === "completed").length}/${backlog.length} tasks done.`);
}

// Final summary
const completed = backlog.filter(t => t.status === "completed").length;
const failed = backlog.filter(t => t.status === "failed").length;
const pending = backlog.filter(t => t.status === "pending").length;

await phase("Loop Complete");
await log(`Iterations: ${iteration} | Completed: ${completed} | Failed: ${failed} | Pending: ${pending}`);

return {
  iterations: iteration,
  completed,
  failed,
  pending,
  results
};
